import Centralizer from "@/components/general/Centralizer";
import Spinner from "@/components/general/Spinner";
import { ModalProvider } from "@/contexts/ModalContext";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";

import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        <Suspense
          fallback={
            <Centralizer>
              <Spinner />
            </Centralizer>
          }
        >
          <ModalProvider>{children}</ModalProvider>
        </Suspense>
      </body>
    </html>
  );
}
